### PR TITLE
feat: pass secrets to build

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
Make it possible to pass secrets to docker build

### CODE REVIEW

**Comment by AlexanderBrevig** [comment]
Closes #123

**Review by bvestli — COMMENTED** [review]
Should we have a test for this feature?

**Comment by AlexanderBrevig** [comment]
> Should we have a test for this feature?

Nice catch! Added test now

**Comment by AlexanderBrevig** [comment]
The test, while only testing happy path, will fail if something has gone wrong.
image

**Comment by Glenn-Terjesen** [comment]
fixes #123

**Pull request merged**
