### PR TITLE
feat[#123]: build-args

### PR DESCRIPTION
**Pull request by Glenn-Terjesen**
- Add [build_args](https://docs.docker.com/reference/cli/docker/buildx/build/#build-arg) as input variable
- Bump versions
- Name jobs @hw-knowit 👍

### CODE REVIEW

**Review by bvestli — COMMENTED** [review]
Should there be a test with using build args as well?

**Comment by Glenn-Terjesen** [comment]
> Should there be a test with using build args as well?

yes, but how? :-) 
We need to verify that the build arg is set somehow (without pushing to jfrog artifactory)
let's think about it

**Comment by Glenn-Terjesen** [comment]
> > Should there be a test with using build args as well?
> 
> yes, but how? :-) We need to verify that the build arg is set somehow (without pushing to jfrog artifactory) let's think about it

Implemented test procedure

**Review by bvestli — APPROVED** [review]
Nice!

**Comment by Glenn-Terjesen** [comment]
not working as it should - to messy

**Pull request closed without merging**
